### ISSUE TITLE
Connecting a GRBL usb machine on linux

### ISSUE THREAD

**Issue by niekiebasson-dev** [barebaric/rayforge#20]
Good day.

The Bug
When trying to connect my Grbl controlled CNC with Rayforge, no port selection window appears when selecting "GRBL (Serial)" in the machine preferences. I have tried with Version 0.20.2post5 Version 0.20.2post4 and the stable versions 0.20.1 and 0.20.2. Unfortunately none of the "Serial" options opened a selection box from where I can select the port or device to use with Rayforge. I have noticed on a Youtube video https://www.youtube.com/watch?v=5g8ivET-c0w&t=84s at 1:36 the video shows a selection box for the port selection as well as baudrate where my installation does not give these options.

Will you be able to assist?

Screenshot of setup page.
https://github.com/user-attachments/assets/e61d952d-a16b-4939-9dad-f7415cfd95db

Screenshot of system details 
https://github.com/user-attachments/assets/8d1b7f5a-b403-4048-b464-9158aaa39c28

https://github.com/user-attachments/files/22256448/rayforge_debug_2025-09-10_16-06-56.zip

**Comment by knipknap** [comment]
Does the user that you are using have permission to read serial ports?

What do you see when you open a terminal and type "groups"?

**Comment by niekiebasson-dev** [comment]
Thank you for the prompt response.
I see the following
#USERNAME adm tty dialout cdrom sudo dip plugdev users lpadmin systemd-journal

**Comment by knipknap** [comment]
That is correct, `dialout` should give you permission to use serial ports. I see that you are running from a git commit; how did you install?

What do you see executing `ls -l /dev/ttyS*`?

**Comment by niekiebasson-dev** [comment]
That would be a list,  **crw-rw---- 1 root dialout 4, 64 Sep 10 18:30 /dev/ttyS0 to 31** but no ttyACM0.

**Comment by knipknap** [comment]
Hrm, that is all perfectly fine. I think I was on the wrong track and this is not related to your serial config itself at all.

Can you try to delete your config (rm -R ~/.config/rayforge) and see if that changes anything?

If it does not, can you try running from the command line like so:

`rayforge --loglevel DEBUG`

to see if there is any relevant log output?

**Comment by niekiebasson-dev** [comment]
When entering:~$ rm -R ~/.config/rayforge
rm: cannot remove '/home/blou/.config/rayforge': No such file or directory

still no change after running rayforge --loglevel DEBUG. it does open Rayforge, but no userlog.

On all the times I tried (uninstalling and re-installing), on "Device" Tab it gives a red **Machine Not Connected** with a note as per the screenshot. Would that note be any assistance. If so, how do I get to it? Gives a "Copy Error Details" pop-up but I can't seem to copy it .

https://github.com/user-attachments/assets/07406a53-d8cc-48fb-909c-bc3ba50a96bf

**Comment by knipknap** [comment]
The error on the device page is correct, because without the serial configuration Rayforge cannot connect to the device.

Are you saying that no logs are printed to CLI at all? I can't think of any way this could happen. Some logs are ALWAYS printed.

**Comment by niekiebasson-dev** [comment]
Log output downloaded
[rayforge_debug_2025-09-10_19-38-27.zip](https://github.com/user-attachments/files/22259839/rayforge_debug_2025-09-10_19-38-27.zip)

**Comment by knipknap** [comment]
Ah, you are thinking about something else - I mean CLI output, not the in-app debug log.

**Comment by knipknap** [comment]
I also just added two commits:
- one to warn if there are permission issues (not likely to help as we excluded that as the source of your problem)
- one that changes how the UI is updated, possibly fixing the error

**Comment by niekiebasson-dev** [comment]
Hi 

Have done the update to Version 0.20.2post2,1also restarted the PC. Same results for opening from snapstore as well as terminal rayforge --loglevel DEBUG

Log files from  DEBUG run
[rayforge_debug_2025-09-10_22-11-48.zip](https://github.com/user-attachments/files/22262185/rayforge_debug_2025-09-10_22-11-48.zip)

And Screenshot
<img width="922" height="922" alt="Image" src="https://github.com/user-attachments/assets/c7212436-07e2-4165-93cb-38639eed4ae3" />

**Comment by knipknap** [comment]
I am afraid I really need the logs from the terminal. The log files in the debug file you sent only contain network logging, which is empty because no connection is attempted yet.

The CLI logs from the terminal are what would really be required to debug it.

**Comment by niekiebasson-dev** [comment]
Good morning.

Please bare with me as I am fairly new to Linux. 
I played around a bit to see how I will be able to get the script from the terminal. Looks like I got it right.

[typescript.zip](https://github.com/user-attachments/files/22270791/typescript.zip)

**Comment by knipknap** [comment]
Ahh, awesome, that contains the error!

```
Traceback (most recent call last):
  File "/snap/rayforge/262/lib/python3.12/site-packages/rayforge/shared/tasker/task.py", line 89, in run
    await self._task
  File "/snap/rayforge/262/lib/python3.12/site-packages/rayforge/machine/models/machine.py", line 140, in _rebuild_driver_instance
    new_driver.setup(**self.driver_args)
  File "/snap/rayforge/262/lib/python3.12/site-packages/rayforge/machine/driver/grbl_serial.py", line 63, in setup
    SerialTransport.check_serial_permissions_globally()
  File "/snap/rayforge/262/lib/python3.12/site-packages/rayforge/machine/transport/serial.py", line 53, in check_serial_permissions_globally
    all_ports = list_ports.comports()
                ^^^^^^^^^^^^^^^^^^^^^
  File "/snap/rayforge/262/lib/python3.12/site-packages/serial/tools/list_ports_linux.py", line 102, in comports
    for info in [SysFS(d) for d in devices]
                 ^^^^^^^^
  File "/snap/rayforge/262/lib/python3.12/site-packages/serial/tools/list_ports_linux.py", line 48, in __init__
    num_if = int(self.read_line(self.usb_device_path, 'bNumInterfaces'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

So somehow Rayforge fails to read your serial ports, which causes the UI to fail before it can be built. This is highly likely a permission issue after all.

I now made two changes:
- Improved the error message on the device page for this particular case.
- Extended the Snap with a serial permission slot.

Can you test again with the latest version?

If it still does not work, execute the following on the CLI:

```
snap connections rayforge
sudo snap connect rayforge:serial-port
snap connections rayforge
```

After restarting Rayforge, it should then work.

**Comment by niekiebasson-dev** [comment]
Ha, a step closer and that's Awesome. It does show the port selection box, as well as Baud rate. I can select the Baud rate, but I'm unable to select or "open" the Port Selection Box.

[session_log.txt](https://github.com/user-attachments/files/22276391/session_log.txt)

<img width="1658" height="1082" alt="Image" src="https://github.com/user-attachments/assets/3bbdf55e-19da-4539-a12c-cc8b406ccb0e" />

**Comment by knipknap** [comment]
Cool, did you execute the commands in the terminal?

```
snap connections rayforge
sudo snap connect rayforge:serial-port
snap connections rayforge
```

**Comment by niekiebasson-dev** [comment]
Have done it a couple of times, with a restart. Think it should be the first bunch of lines in the script log that I attached. 
Wen entering **error: snap "snapd" has no "serial-port" interface slots** I get this _error: snap "snapd" has no "serial-port" interface slots_

**Comment by knipknap** [comment]
I was finally able to reproduce the issue on my own machine, and I just pushed a fix (24211dc). For it to work, you will have to

1. Update to the latest Rayforge edge release.
1. Plug your laser into a USB port.
2. Open a terminal
3. **Execute the following command**: `sudo snap set system experimental.hotplug=true`
4. **Execute the following command**: `sudo snap connect rayforge:serial-port`. This time, it should not give you the error. That is assuming your laser is correctly connected to the USB port.
5. Start Rayforge (e.g. `rayforge --loglevel DEBUG`)

You should only have to do this once - after that it should work even after upgrades.

If it worked correctly, the following command `snap connections rayforge` should show something connected in the line "serial-port". Example from my machine:

```
$ snap connections rayforge 
Interface               Plug                      Slot                            Notes
camera                  rayforge:camera           -                               -
content[gnome-46-2404]  rayforge:gnome-46-2404    gnome-46-2404:gnome-46-2404     -
content[gpu-2404]       rayforge:gpu-2404         mesa-2404:gpu-2404              -
content[gtk-3-themes]   rayforge:gtk-3-themes     gtk-common-themes:gtk-3-themes  -
content[icon-themes]    rayforge:icon-themes      gtk-common-themes:icon-themes   -
content[sound-themes]   rayforge:sound-themes     gtk-common-themes:sound-themes  -
dbus                    -                         rayforge:rayforge               -
desktop                 rayforge:desktop          :desktop                        -
desktop-legacy          rayforge:desktop-legacy   :desktop-legacy                 -
gsettings               rayforge:gsettings        :gsettings                      -
home                    rayforge:home             :home                           -
network                 rayforge:network          :network                        -
network-bind            rayforge:network-bind     :network-bind                   -
opengl                  rayforge:opengl           :opengl                         -
removable-media         rayforge:removable-media  -                               -
serial-port             rayforge:serial-port      :usbserial                      manual
shared-memory           rayforge:shared-memory    -                               -
wayland                 rayforge:wayland          :wayland                        -
x11                     rayforge:x11              :x11                            -
```

This is the line:

```
serial-port             rayforge:serial-port      :usbserial                      manual
```

**Comment by niekiebasson-dev** [comment]
Good day KnipKnap

That worked perfectly. Machine connects. There is another problem now though.
I have set the machine to home when connecting, Machine does not Home on startup and the home button is also not available. See screenshot. Log file from Rayforge Status bar also attached. 

Ps. Your assistance and dedication is HIGHLY Appreciated


<img width="1854" height="1168" alt="Image" src="https://github.com/user-attachments/assets/342850e4-f3a7-4017-8ced-35d2a58adba9" />

[rayforge_debug_2025-09-12_10-54-35.zip](https://github.com/user-attachments/files/22294044/rayforge_debug_2025-09-12_10-54-35.zip)

**Comment by knipknap** [comment]
Ahh, progress, that is great! Thank you for all the debugging!

The logs look like the machine is connected and communicating correctly.

The home button and homing does not work because your machine is in an ALARM status - in your debug log, the very first message from your device is the ALARM. This indicates an issue with your machine that Rayforge cannot really do anything about. Perhaps something like the lid not being closed, or another issue with the machine itself?

**Comment by niekiebasson-dev** [comment]
No lid or anything like that on my machine. Don't know if End stops on my machine might somehow have something to do with it. When I open bCNC it also gives alarm when I start it up, as soon as I Home the machine with/in bCNC the alarm goes away. Tried homing on bCNC and then Rayforge but the Alarm in Rayforge still persists.

**Comment by knipknap** [comment]
I just added support for clearing alarms - with a button in the main window, and also as an automatic "on connect" setting.

<img width="589" height="344" alt="Image" src="https://github.com/user-attachments/assets/c48a4cbb-6810-4cdc-b2ba-9cda7ebb3583" />

Does that help?

**Comment by niekiebasson-dev** [comment]
Good day KnipKnap

Rayforge connected, cleared Alarm and did its firs laser test on my CNC last night.

Thank you very, Very much!

**Comment by knipknap** [comment]
Awesome, thank you for your patience!
